redcloth_hard_breaks: false
pygments:  true
permalink: /:categories/:title/
paginate:  5

exclude:
  - README.rdoc

title:        "sem4r: adwords ruby library"
url:          http://www.sem4r.com
feed:         /atom.xml
description:  Adwords client library for ruby
comment:      Adwords client library for ruby

author:
  name:       sem4r
  email:      sem4r@sem4r.com
  twitter:    sem4r_
  
disqus:
    id:         sem4r

nav:
    - name:     Blog
      url:      /
    - name:     About
      url:      /about/
    - name:     Contact
      url:      mailto:sem4r-at-dotcom-after-sem4r

